### ISSUE TITLE
Viewer 

### ISSUE THREAD

**Issue by max482022** [AECgeeks/ifc-pipeline#12]
Is it possible to replace surfer2 with xeokit-bim-viewer-app? It's just that there are no tools for work in surfer2, for example, cross-section or measurement or on gemini-viewer it also uses gltf format, only there are no matadany

**Comment by max482022** [comment]
or on gemini-viewer it also uses GIF format, only there are no matadany

**Comment by aothms** [comment]
Another candidate is bimsurfer v3 https://github.com/opensourceBIM/BIMsurfer/ it also has sections and measurement functionality.

I'm not entirely sure about the effort to support xeokit, but I would not immediately see this in scope of our version ifc-pipeline. We have to review license differences also, not sure about MIT + AGPL. If you want to work on it, I can see if I can provide advise where needed. At least the IfcConvert bit is shared I think.

Another alternative would be that you keep ifc-pipeline as is and build your own web-based front-end around xeokit that uses the converted glTF from ifc-pipeline. Not sure if xeokit needs their own format or that it can also load relatively well from the .glb that IfcConvert provides directly.

**Comment by max482022** [comment]
There is no complete grouping of objects by category in the selection tree. How to solve it
![2022-04-08_16-23-57](https://user-images.githubusercontent.com/96478852/162444717-822f86c5-57e0-4d35-ba7d-e846cfa47ce1.png)
?

**Comment by aothms** [comment]
There is no grouping by category, it's only by containment. The walls and furniture you highlighted are all contained in building storey "Nivel 1".
