### ISSUE TITLE
no conversion

### ISSUE THREAD

**Issue by max482022** [AECgeeks/ifc-pipeline#13]
Good afternoon.
1. launched ./run_debug.sh .
2 .Downloaded the ifc file.
3. The progress page has opened, but there is no conversion.
Please tell me what is the problem?
![image](https://user-images.githubusercontent.com/96478852/171567358-7d1df7a6-1f28-4c64-a0b9-02e9dc090cd5.png)

**Comment by aothms** [comment]
Did you follow the installation instructions for local development? https://github.com/AECgeeks/ifc-pipeline#local-development

What's the output in the python terminal?

**Comment by max482022** [comment]
![image](https://user-images.githubusercontent.com/96478852/171576507-243a74b6-00b0-41b2-9b05-ec094f78a4d8.png)

**Comment by max482022** [comment]
Yes, I did it according to the instructions https://github.com/AECgeeks/ifc-pipeline#local-development

**Comment by max482022** [comment]
[ValueError_ not enough values to unpack (expected 2, go.pdf](https://github.com/AECgeeks/ifc-pipeline/files/8821700/ValueError_.not.enough.values.to.unpack.expected.2.go.pdf)

**Comment by aothms** [comment]
> File "/opt/ifc/application/main.py", line 284, in get_model

Is the `/m/` route which serves the various conversion artefacts when viewing the model. You're not supposed to view this route in your browser directly, as it is only the resources for the viewer.

Your previous issue was that there is no conversion progress when your are on the `/p/` route.

Please outline the steps you have followed.

**Comment by max482022** [comment]
[root.pdf](https://github.com/AECgeeks/ifc-pipeline/files/8822051/root.pdf)

**Comment by aothms** [comment]
Can you share the file you selected?

**Comment by aothms** [comment]
Actually, try again after https://github.com/AECgeeks/ifc-pipeline/commit/ea390a2daa6a33cf513c1fa75cfa906222719cfd I think this is a more sensible default for local dev mode.

**Comment by max482022** [comment]
[505-1_10_Tragwerk.zip](https://github.com/AECgeeks/ifc-pipeline/files/8822163/505-1_10_Tragwerk.zip)

**Comment by max482022** [comment]
application/run_debug.sh 
Specified- environment=development FLASK_APP=main.py FLASK_DEBUG=1 python3 -m flask run -h 0.0.0.0 --with-threads
Now the conversion went and stopped at 3% with an error:
 Restarting with stat
 * Debugger is active!
 * Debugger PIN: 115-735-468
Using 2 threads per worker
195.34.243.240 - - [02/Jun/2022 11:54:47] "GET / HTTP/1.1" 200 -
195.34.243.240 - - [02/Jun/2022 11:54:47] "GET /static/main.css HTTP/1.1" 304 -
195.34.243.240 - - [02/Jun/2022 11:54:59] "POST / HTTP/1.1" 200 -
ifc_validation_task /opt/ifc/application/worker.py 0.0 3.96
195.34.243.240 - - [02/Jun/2022 11:54:59] "GET /p/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -
195.34.243.240 - - [02/Jun/2022 11:54:59] "GET /static/main.css HTTP/1.1" 304 -
195.34.243.240 - - [02/Jun/2022 11:54:59] "GET /pp/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -
195.34.243.240 - - [02/Jun/2022 11:55:00] "GET /pp/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -
195.34.243.240 - - [02/Jun/2022 11:55:01] "GET /pp/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -
195.34.243.240 - - [02/Jun/2022 11:55:02] "GET /pp/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -
195.34.243.240 - - [02/Jun/2022 11:55:03] "GET /pp/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -
195.34.243.240 - - [02/Jun/2022 11:55:04] "GET /pp/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -
195.34.243.240 - - [02/Jun/2022 11:55:05] "GET /pp/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -
195.34.243.240 - - [02/Jun/2022 11:55:07] "GET /pp/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -
195.34.243.240 - - [02/Jun/2022 11:55:08] "GET /pp/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -
195.34.243.240 - - [02/Jun/2022 11:55:09] "GET /pp/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -
xml_generation_task /opt/ifc/application/worker.py 3.96 7.92
195.34.243.240 - - [02/Jun/2022 11:55:10] "GET /pp/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/opt/ifc/application/worker.py", line 349, in process
    do_process(id)
  File "/opt/ifc/application/worker.py", line 344, in do_process
    raise RuntimeError()
RuntimeError
195.34.243.240 - - [02/Jun/2022 11:55:11] "GET /pp/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -
195.34.243.240 - - [02/Jun/2022 11:55:12] "GET /pp/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -
195.34.243.240 - - [02/Jun/2022 11:55:13] "GET /pp/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -
195.34.243.240 - - [02/Jun/2022 11:55:14] "GET /pp/QpWUvBQerOOvjnOFHzPoiyIYaVMUzOPz HTTP/1.1" 200 -

**Comment by max482022** [comment]
Thanks. It worked.
Rebooted the server and the conversion is 100%
