### ISSUE TITLE
there is no access to ifc-pepiline from the internet.

### ISSUE THREAD

**Issue by max482022** [AECgeeks/ifc-pipeline#14]
Hello again.
The certificate was received by the command:
./init.sh (my.domain.)

Launched docker-compose up -d
Starting ifc_certbot_1 ... done
Starting ifc_db_1 ... done
Starting ifc_redis_1 ... done
Starting ifc_worker_1 ... done
Starting ifc_frontend_1 ... done
Starting ifc_nginx_1 ... done
The domain has A record with the IP address of the virtual machine.
Open port 80 on the domain.
Why can't I establish a connection when switching to a domain?

Please advise, where is the catch?

**Comment by aothms** [comment]
Maybe check the logs for nginx (`docker-compose logs nginx`)? There might be something there. Otherwise we can't advise much on the networking, we're simply using docker-compose.

**Comment by max482022** [comment]
Yes, you're right.
nginx_1     | nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx_1     | nginx: configuration file /etc/nginx/nginx.conf test is successful
nginx_1     | 2022/06/02 11:00:59 [emerg] 7#7: bind() to 0.0.0.0:443 failed (98: Address in use)
nginx_1     | nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx_1     | 2022/06/02 11:00:59 [emerg] 7#7: bind() to 0.0.0.0:80 failed (98: Address in use)
nginx_1     | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx_1     | 2022/06/02 11:00:59 [emerg] 7#7: bind() to [::]:80 failed (98: Address in use)
nginx_1     | nginx: [emerg] bind() to [::]:80 failed (98: Address in use)
nginx_1     | 2022/06/02 11:00:59 [notice] 9#9: signal process started
nginx_1     | 2022/06/02 11:00:59 [alert] 9#9: kill(6, 1) failed (3: No such process)
nginx_1     | nginx: [alert] kill(6, 1) failed (3: No such process)
nginx_1     | nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx_1     | nginx: configuration file /etc/nginx/nginx.conf test is successful
nginx_1     | 2022/06/02 11:04:31 [notice] 10#10: signal process started
What is the best way for me to do, please advise?

**Comment by aothms** [comment]
>  nginx_1 | nginx: [emerg] bind() to [::]:80 failed (98: Address in use)

Address in use. There is already something else listening on port 80.

Use `netstat -peanut`.

**Comment by max482022** [comment]
root@gubanovli2-vps-2:/opt/ifc# netstat -peanut
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      0          53987      24078/sshd: root@pt
tcp        0      0 127.0.0.1:39115         0.0.0.0:*               LISTEN      0          20226      535/containerd
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      113        20012      607/redis-server 12
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      0          82379      27055/docker-proxy
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      101        17258      489/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          19996      582/sshd: /usr/sbin
tcp        0    224 77.222.52.18:22         195.34.243.240:64780    ESTABLISHED 0          52111      24078/sshd: root@pt
tcp        0      0 77.222.52.18:22         195.34.243.240:64781    ESTABLISHED 0          54289      24185/sshd: root@no
tcp6       0      0 ::1:6010                :::*                    LISTEN      0          53988      24078/sshd: root@pt
tcp6       0      0 ::1:6379                :::*                    LISTEN      113        20013      607/redis-server 12
tcp6       0      0 :::80                   :::*                    LISTEN      0          82419      27069/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      0          20007      582/sshd: /usr/sbin
udp        0      0 127.0.0.53:53           0.0.0.0:*                           101        17257      489/systemd-resolve
root@gubanovli2-vps-2:/opt/ifc# netstat -tulpn | grep --color :80
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      27055/docker-proxy
tcp6       0      0 :::80                   :::*                    LISTEN      27069/docker-proxy


When starting docker-compose up -d
do I understand correctly that docker-proxy occupies port 80 and therefore nginx does not connect?

**Comment by max482022** [comment]
Is it possible to change port 80 to port 8080 in docker proxy?

**Comment by max482022** [comment]
Good afternoon

There are no errors, why am I when I switch to the domain, nothing happens.


root@gubanovli2-vps-2:/opt/ifc# docker-compose logs nginx
Attaching to ifc_nginx_1
nginx_1     | nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx_1     | nginx: configuration file /etc/nginx/nginx.conf test is successful
nginx_1     | 2022/06/03 08:48:34 [notice] 11#11: signal process started
root@gubanovli2-vps-2:/opt/ifc#


Please tell me , I 've already broken my whole head

**Comment by max482022** [comment]
uwsgi --http-socket :5000 --plugin python3 --module wsgi:app
open("./python3_plugin.so"): No such file or directory [core/utils.c line 3732]
!!! UNABLE to load uWSGI plugin: ./python3_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.20 (64bit) on [Fri Jun  3 13:06:46 2022] ***
compiled with version: 9.4.0 on 02 June 2022 04:57:17
os: Linux-5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022
nodename: ubuntu1
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/admin1
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 63453
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :5000 fd 3
Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55815904c8e0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
ModuleNotFoundError: No module named 'wsgi'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 2092, cores: 1)

**Comment by aothms** [comment]
> maybe uwsgi doesn't start.

We don't use uwsgi but gunicorn. If you hit nginx without gunicorn running it will give you a 504 Gateway Timeout so that's not the issue.

> Can I download Flash using uWSGI without nginx?

You can set it up in anyway you like. It's just a simple Flask application. We chose nginx+gunicorn in docker-compose but any other way is fine too.

Is the domain really properly configured? Does it work if you substitute ifc-pipeline with something else (e.g `python3 -m http.server`).

**Comment by Gubanov-482022** [comment]
Which command should I run gunicorn with? I'm running I have an error the app module was not found.

**Comment by aothms** [comment]
https://github.com/AECgeeks/ifc-pipeline/blob/master/docker-compose.yml#L24

**Comment by max482022** [comment]
root@ubuntu1:/home/admin1/ifc/application# python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...

localhost:8000 not responding

**Comment by max482022** [comment]
firewall  inactive.


And more.Launched the cannon root manually. Went to the address with the host 5000. Uploaded the models to the IFC, and the error:
File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py ", line 122, in connection
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: failed to connect to server: connection denied
Is the server running on the "localhost" host (127.0.0.1) and accepting
TCP/IP connections on port 5432?

**Comment by aothms** [comment]
You can run it manually but then you need to make sure postgres and redis are working or disable the dependencies using env vars as is done in run_debug.sh

**Comment by max482022** [comment]
And in which file is this done?

**Comment by max482022** [comment]
502 Bad Gateway, is there a problem with the ports?

**Comment by aothms** [comment]
Check docker logs or command line output for exceptions when running the
python server code.

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op ma 7 apr 2025 16:14 schreef max482022 ***@***.***>:
