### ISSUE TITLE
bimsurfer opens, the download goes on forever and the model is not reflected

### ISSUE THREAD

**Issue by max482022** [AECgeeks/ifc-pipeline#17]
In debugging mode, the model opens, but not in debugging mode, the model is loaded, the conversion is 100% and the bimsurfer opens, the download goes on forever and the model is not reflected
![image](https://user-images.githubusercontent.com/96478852/172386440-79c9a9da-989e-4240-bf57-16170163db13.png)
Tell me please

**Comment by max482022** [comment]
Thomas, please tell me, all hope is on YOU.

**Comment by aothms** [comment]
What URL are you browsing? Why are there `file://` urls here:

![afbeelding](https://user-images.githubusercontent.com/1096535/172578886-dc4032a0-c924-4e84-a6f3-f7af359712bf.png)

> the download goes on forever 

Which download exactly?

> In debugging mode, the model opens, but not in debugging mode, the model is loaded

What do you precisely mean by this?

**Comment by max482022** [comment]
In debug mode when I run ./run_debug.sh . Everything works fine

I entered the docker-compose up -d command.
Then I go to the domain and open the IFC pipeline browser. I load the IFC model, the conversion is 100%, the viewer opens without the model/

Uploading 20220608_123059_edit1.mp4…

**Comment by max482022** [comment]
https://ifc.uks48.ru/

**Comment by Gubanov-482022** [comment]
Thomas, have you looked?

**Comment by aothms** [comment]
You have an older version of BIMsurfer

You're version (using chrome inspector with pretty print)

![afbeelding](https://user-images.githubusercontent.com/1096535/172604925-64bb49f3-880a-44eb-9b95-e3bb913e8c9f.png)

Version in submodule

![afbeelding](https://user-images.githubusercontent.com/1096535/172605456-8f5320c6-d58d-44f0-93c7-b61205c3b298.png)

https://github.com/AECgeeks/BIMsurfer2/blob/200535ad90f767c7c44524315a0bff80f33ae8e3/bimsurfer/src/MultiModal.js

Likely your submodule isn't updated, try:

~~~
git submodule update
docker-compose up -d --build
~~~
