### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Moult** [AECgeeks/ifc-pipeline#2]
I've added it to the AEC free software directory, assuming it is free software, but was not sure what the license is: https://wiki.osarch.org/index.php?title=AEC_Free_Software_directory#OpenBIM_Management

**Comment by aothms** [comment]
Thanks, it's MIT https://github.com/AECgeeks/ifc-pipeline/blob/master/application/main.py#L5 I'll make it more explicit later.

**Comment by Moult** [comment]
Cheers :)
