### ISSUE TITLE
GET http://127.0.0.1:5000/static/bimsurfer/lib/three/r140/three.module.js net::ERR_ABORTED 404 (NOT FOUND)

### ISSUE THREAD

**Issue by sadsasuke** [AECgeeks/ifc-pipeline#22]
Hi, i am trying to run locally with the instructions of linux in readme.
I am getting this issue .
after the i click submit all screens are empty and model doesnt load 
GET http://127.0.0.1:5000/static/bimsurfer/lib/three/r140/three.module.js net::ERR_ABORTED 404 (NOT FOUND)
is the issue what i can see.  I have placed on this link the exact files in repo but cant seem to work.

any suggesstions will be helpful

**Comment by aothms** [comment]
Have you clone with recursive (or `git submodule update --init --recursive`). bimsurfer is a git submodule in this repo.

**Comment by sadsasuke** [comment]
hi, yes cloned recursively and installed all the requirements

![image](https://github.com/AECgeeks/ifc-pipeline/assets/61054259/754f1d63-9637-4f0d-a6d3-7185db55ffc4)

![image](https://github.com/AECgeeks/ifc-pipeline/assets/61054259/37c506b5-766c-4f47-aa32-ada5f7356ca4)

![image](https://github.com/AECgeeks/ifc-pipeline/assets/61054259/a00c4722-81f1-44ab-ba92-683ee76d8154)

**Comment by sadsasuke** [comment]
i have been trying all day. but cant seem to find the issue
.
Basically I follow all your instructions.

**Comment by aothms** [comment]
Hm, that log is helpful, I see now that path is indeed not correct

https://github.com/AECgeeks/ifc-pipeline/blob/6abb9412ffedd4a9a72b9f8702c6af5106210dac/application/templates/viewer.html#L22

https://github.com/AECgeeks/ifc-pipeline/blob/6abb9412ffedd4a9a72b9f8702c6af5106210dac/application/templates/viewer.html#L36

Can you try updating to:

    "/static/bimsurfer/src/v2/bimsurfer/lib/three/r140/three.module.js"

**Comment by sadsasuke** [comment]
hi, i updated and thanks for that but now this  has arrived
![image](https://github.com/AECgeeks/ifc-pipeline/assets/61054259/83771fce-74b8-4cd2-b457-4770f8d6280d)

**Comment by sadsasuke** [comment]
hi the issue is resolved. i put the path you sent incorrectly

**Comment by sadsasuke** [comment]
thanks @aothms

**Comment by aothms** [comment]
Glad it's resolved. Would you mind sending in a Pull request with the correction?
