### ISSUE TITLE
Dynamic Property Update from XML

### ISSUE THREAD

**Issue by saintcodec** [AECgeeks/ifc-pipeline#25]
Hi,

I’ve been exploring the ifc-pipeline project and I’m very interested in its potential for dynamically updating properties in IFC models.
From what I understand, the properties are stored separately in an XML file after conversion by IfcConvert. I’m wondering if this setup could allow dynamic updates to the IFC model properties (such as sensor data) without the need to reload the 3D geometry each time.
For example, instead of reloading the entire model, we could update only the XML file with new property data, and then reflect those updates in the viewer dynamically.
Do you think this could be achievable with the current architecture? What would be the best approach to handle such dynamic updates?

Looking forward to your thoughts!

Best regards,
Amin

**Comment by aothms** [comment]
Hi Amin,

I don't think it's wise to modify an XML text file on disk concurrently from multiple server sessions. You can convert the XML to JSON https://github.com/AECgeeks/ifc-pipeline/blob/master/application/process_xml_to_json.py And then subsequently inject into a document-db or postgres with some json fields.

Thomas

**Comment by saintcodec** [comment]
Hi Thomas,

Thanks for the quick response! Your suggestion sounds great. I’ll give it a try.
Thanks again for the guidance!

Best,
Amin
